- .travis.yml
> Code Coverage

- main_test.go
- styles/api_test.go
> Coverage for Styles(themes)

- main.go
- main_test.go
> Handling multiple files

- .goreleaser.yml
- main.go
- main_test.go
Release with [gorelease](https://github.com/goreleaser/goreleaser).
closes #25
https://github.com/toshimaru/nyan/releases/tag/v0.0.0
- [GoReleaser](https://goreleaser.com/)
> Release with gorelease

- .goreleaser.yml
> Update .goreleaser.yml / brew formula release

- main_test.go
- styles/abap.go
- styles/api_test.go
- styles/emacs.go
- styles/monokailight.go
- styles/pygments.go
- styles/solarized-light.go
closes #26 
- abap
- emacs
- monokailight
- pygments
- solarized-light
> Add Light themes

- go.mod
- go.sum
- main.go
> Fix Windows colors

- .github/workflows/go.yml
- main_test.go
- styles/solarized-dark.go
- [actions/setup-go: Set up your GitHub Actions workflow with a specific version of Got](https://github.com/actions/setup-go)
- [Virtual environments for GitHub Actions - GitHub Help](https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environments)
- [Configuring a workflow - GitHub Help](https://help.github.com/en/articles/configuring-a-workflow#configuring-a-build-matrix)
> CI with GitHub Actions

- .github/workflows/goreleaser.yml
- .github/workflows/release.yml
- [Events that trigger workflows - GitHub Help](https://help.github.com/en/articles/events-that-trigger-workflows#webhook-events)
> Add goreleaser workflow

- .github/workflows/go.yml
- .github/workflows/release.yml
- .travis.yml
Folowing #39
resolves #30 
- [GoReleaser](https://goreleaser.com/)
- [新 GitHub Actions 入門 - 生産性向上ブログ](https://www.kaizenprogrammer.com/entry/2019/08/18/205010)
> Release Automation

- .github/workflows/go.yml
- .github/workflows/release.yml
[goreleaser/goreleaser-action: GitHub Action for GoReleaser](https://github.com/goreleaser/goreleaser-action)
> Use goreleaser/goreleaser-action

- .github/workflows/go.yml
- .github/workflows/release.yml
- go.mod
- go.sum
- main.go
- main_test.go
> feature: Add list-themes option

- README.md
- main.go
> Add Available Themes

- main.go
- main_test.go
- testdata/dummy.go.unknown
resolves #53
- Add language option
- Better loop handling when filename is invalid
- Modify sample code for `--list-themes`
> Add language option

- main.go
> Indent code for list-themes

- .github/workflows/coverage.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
- README.md
- go.mod
[Go 1.14 Release Notes - The Go Programming Language](https://golang.org/doc/go1.14)
> Use go v1.14

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/release.yml
- file rename
- actions/setup-go@v2-beta -> actions/setup-go@v2
> GitHub Action Update

- main.go
Fix it!
> // FIXME: use PrintErrln after upstream is fixed
> Use PrintErrln instead of PrintErr

- main.go
- main_test.go
> Number option support

- README.md
<details>
<summary> Old OG</summary>
</details>
<details>
<summary> New OG</summary>
</details>
> Update OG image / Add `Music by daniwell` credit

- .goreleaser.yml
ref. https://goreleaser.com/customization/build/
> Set goreleaser ldflag to set proper version

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/release.yml
- .github/workflows/reviewdog.yml
- go.mod
```
$ go mod edit -go=1.22
```
> Bump go from 1.21 to 1.22
