toshimaru/nyan

- go.mod
- main.go
- main_test.go
- if stdout is used, output with the highlight
- if`>` redirect is used, output without the highlight.
- Add module: https://github.com/mattn/go-isatty
- Use named return value
> Better Output handling

- .travis.yml
- README.md
- main.go
resolves #18 
```console
$ go run main.go -h
Colorized cat
Usage:
nyan [FILE] [flags]
Examples:
$ nyan FILE
Flags:
-h, --help           help for nyan
-t, --theme string   color theme
available themes: [dracula monokai solarized-dark swapoff vim] (default "monokai")
-v, --version        show version
```
> Available themes

- README.md
- main.go
- main_test.go
```console
$ GO111MODULE=on go test ./... -cover
ok  	github.com/toshimaru/nyan	0.175s	coverage: 86.7% of statements
ok  	github.com/toshimaru/nyan/styles	0.016s	coverage: 100.0% of statements
```
```console
$ GO111MODULE=on go test ./... -cover
ok  	github.com/toshimaru/nyan	0.100s	coverage: 80.0% of statements
ok  	github.com/toshimaru/nyan/styles	(cached)	coverage: 100.0% of statements
```
> Add main test / Update description

- go.mod
- go.sum
Reverts toshimaru/nyan#36
Because #35 also includes the same change.
> Revert "Bump github.com/mattn/go-isatty from 0.0.8 to 0.0.9"

- main.go
- main_test.go
- Set Stdout and Stderr on init func
- Use `PrintErr` instead of `Print`
- TODO: fix upstream `PrintErrln`
- Use `var` statement instead of `NewBufferString`
> Better Standard Error Output using PrintErr

- main.go
- main_test.go
closes #57
```console
$ nyan x go.mod
open x: no such file or directory
module github.com/toshimaru/nyan
go 1.13
require (
github.com/alecthomas/chroma v0.6.8
github.com/alecthomas/repr v0.0.0-20181024024818-d37bc2a10ba1 // indirect
github.com/dlclark/regexp2 v1.1.8 // indirect
github.com/mattn/go-colorable v0.1.4
github.com/mattn/go-isatty v0.0.10
github.com/spf13/cobra v0.0.5
github.com/stretchr/testify v1.3.0
)
$ echo $?
0
```
```console
$ nyan x
open x: no such file or directory
Error: open x: no such file or directory
Usage:
nyan [OPTION]... [FILE]... [flags]
Examples:
...
```
```console
$  go run main.go -- x go.mod
Error: open x: no such file or directory
module github.com/toshimaru/nyan
go 1.13
require (
github.com/alecthomas/chroma v0.6.8
github.com/alecthomas/repr …
```
> Better error output and exit code

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/release.yml
- .goreleaser.yml
- go.mod
1. Use Go v1.15.
2. Fix the following error.
```
⨯ release failed after 49.01s error=failed to build for darwin_386: cmd/go: unsupported GOOS/GOARCH pair darwin/386
```
3. Fix the deprecation message:
```
DEPRECATED: `brews.github` should not be used anymore, check https://goreleaser.com/deprecations#brewsgithub for more info.
```
> Bump Go version from 1.14 to 1.15

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .goreleaser.yml
Since go module is enabled by default.
> Module-aware mode is enabled by default, regardless of whether a go.mod file is present in the current working directory or a parent directory
[Go 1.16 Release Notes - The Go Programming Language](https://golang.org/doc/go1.16)
> Remove `go mod download`

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .goreleaser.yml
- Fix brew error
- See also. https://github.com/toshimaru/homebrew-nyan/pull/2
- Ignore windows x arm64
- https://goreleaser.com/deprecations/#builds-for-windowsarm64
- see. https://github.com/toshimaru/nyan/issues/119
> Fix goreleaser build error (Use `goreleaser check` instead)

- .github/workflows/reviewdog.yml
- cmd/root.go
- main_test.go
- Use [staticcheck](https://staticcheck.io/) instead of [golint](https://github.com/golang/lint)
- Use `pull_request_target`
- ref. [Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests | GitHub Security Lab](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
- return err when an error occurs
- ioutil → io
- https://go.dev/doc/go1.16#ioutil
> Use staticcheck instead of golint / Remove deprecated ioutil pkg

- .github/workflows/ci.yml
Configure colored output test only if the OS is linux.
- [gfx/example-github-actions-with-tty: A demo repository to prepare TTY for GitHub Actions step scripts](https://github.com/gfx/example-github-actions-with-tty)
- https://github.com/actions/runner/issues/241
> Colored output test by enabling TTY

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .goreleaser.yml
Update goreleaser configuration (`.goreleaser.yml`).
ref. https://github.com/goreleaser/goreleaser/blob/4526c5b6813ade905f9658467c3a85aa25bdc9b9/.goreleaser.yaml
- ci: Set fetch-depth: 0 for release
- fix: Remove deprecated option `--rm-dist`, use `--clean` instead
> build: Update `.goreleaser.yml`

- .goreleaser.yml
Fix wrong version info:
```console
❯ nyan -v
version dev
````
- remove mod_timestamp
- chore: Add "Other work" section
> fix: Output correct version

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/release.yml
- .github/workflows/reviewdog.yml
- go.mod
- Bump go version from 1.20 to 1.21
- [Go 1.21 Release Notes - The Go Programming Language](https://tip.golang.org/doc/go1.21)
- Run goreleaser on Linux only
> Bump go from 1.20 to 1.21

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/release.yml
- .github/workflows/reviewdog.yml
- go.mod
This pull request updates the Go version used across the project from `1.22` to `1.23`. The changes affect multiple workflow files and the `go.mod` file to ensure consistency in the build, test, and release processes.
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL20-R20): Updated the `go-version` in the CI workflow to `1.23` for building and testing the project.
* [`.github/workflows/coverage.yml`](diffhunk://#diff-a2115d277b5ca5a2f09a999e53440839cf332b94da177f3d1766334555b0f7c6L14-R14): Updated the `go-version` in the coverage workflow to `1.23` for generating code coverage reports.
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L17-R17): Updated the …
> Bump go from 1.22 to 1.23

- .github/CODEOWNERS
- .github/dependabot.yml
This pull request makes minor adjustments to repository configuration files. It adds a new code owner and updates the Dependabot configuration to remove reviewers for dependency updates.
Repository configuration changes:
* [`.github/CODEOWNERS`](diffhunk://#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7R1): Added `@toshimaru` as a code owner for all files.
* [`.github/dependabot.yml`](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28L7-R10): Removed `@toshimaru` as a reviewer for dependency updates and standardized the `interval` field formatting.
> Remove reviewers in `dependabot.yml`, add `CODEOWNERS` file instead.

- .github/workflows/coverage.yml
This pull request updates the `.github/workflows/coverage.yml` file to transition from CodeClimate to Qlty for coverage reporting. It includes changes to the workflow name, job naming, permissions setup, and the coverage reporting process.
- [example-go/.github/workflows/main.yml at main · qltysh/example-go](https://github.com/qltysh/example-go/blob/main/.github/workflows/main.yml)
- [qltysh/qlty: 💎 Code quality CLI for universal linting, auto-formatting, security scanning, and maintainability](https://github.com/qltysh/qlty)
- [Code Climate Qualityの後継はQlty](https://invokable.net/article/qlty)
* Updated workflow name from "Coverage with CodeClimate" to "Coverage with Qlty."
* Changed job name from `codeclimate-report` to `coverage` and updated the steps to use Qlty's coverage action …
> Code Climate to Qlty

- README.md
This pull request updates the badges in the `README.md` file to use a new service for maintainability and code coverage metrics.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L4-R5): Replaced Code Climate badges with Quality (qlty.sh) badges for maintainability and code coverage.
> chore: Add Qlty badges

- .github/workflows/release.yml
- LICENSE
- README.md
This pull request includes updates to the project metadata and workflow configuration. Key changes involve renaming a GitHub Actions workflow, updating copyright years in the `LICENSE` file, and modifying badges in the `README.md` for better alignment with current workflows.
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L1-R1): Renamed the workflow from "Release with goreleaser" to "Release" for simplicity.
* [`LICENSE`](diffhunk://#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7L3-R3): Updated the copyright years from 2019-2022 to 2019-2025.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-R3): Adjusted badge links to reflect changes in workflow …
>  chore: Simplify release workflow name

- .github/workflows/ci.yml
- .goreleaser.yml
- README.md
- cmd/root.go
closes #44 
- https://github.com/Homebrew/homebrew-core/pull/230045
- Update README.md
- docs: Use official formula instead of brew tap
- docs: Add command sample image
- docs: nyan is now added homebrew-core
- chore: Update descriptions
----
This pull request includes updates to improve consistency in terminology, enhance documentation, and standardize configuration files. The most significant changes involve rephrasing descriptions to use "colorizing" instead of "colored," updating the `README.md` with new installation notes, and standardizing string formatting in configuration files.
* Updated descriptions in `README.md` and `cmd/root.go` to replace "Colored `cat` command" with "Colorizing `cat` command" for consistency and clarity. (`README.md`: …
> docs: Update README.md and command description

- cmd/root.go
- cmd/root_test.go
Disabled completion command provided by Cobra
ref(ja). [cobra で `helpコマンド` を非表示にする](https://enuesaa.dev/posts/go-cobra-disable-help-command)
----
This pull request introduces a change to disable the default shell completion command in the CLI tool and adds a corresponding test to ensure this behavior is enforced.
Shell completion command disabled:
* Set `CompletionOptions.DisableDefaultCmd` to `true` in the `rootCmd` configuration in `cmd/root.go`, preventing the default Cobra shell completion command from being available.
Testing:
* Added `TestCompletionDisabled` in `cmd/root_test.go` to verify that running the `completion` command returns an error and does not produce any output, confirming the completion command is disabled.
> chore: Disabled completion command 

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- .github/workflows/release.yml
- .github/workflows/reviewdog.yml
- go.mod
This pull request updates the Go toolchain configuration and CI workflows to ensure consistency with the version specified in `go.mod`. The main change is switching all GitHub Actions workflows to use the Go version defined in `go.mod` rather than hardcoding a specific version, and explicitly specifying the toolchain version in `go.mod`.
**Go toolchain and workflow configuration:**
* Added `toolchain go1.25.0` to `go.mod` to explicitly specify the required Go toolchain version.
**Continuous Integration workflows:**
* Updated `.github/workflows/ci.yml`, `.github/workflows/coverage.yml`, `.github/workflows/release.yml`, and `.github/workflows/reviewdog.yml` to use `go-version-file: go.mod` in the `actions/setup-go` step, ensuring all workflows use the Go version declared in `go.mod`. …
> Update Go toolchain version from 1.24 to 1.25
